version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.8-browsers
        environment:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: ""
          PGDATABASE: myapp_test
          REDIS_URL: redis://localhost:6379

      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_DB: myapp_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""

      - image: redis:latest

    steps:
      - checkout

      - run:
          name: Install Bundler
          command: |
            gem install bundler -v '2.4.13'

      - run:
          name: Install dependencies
          command: |
            bundle install --path vendor/bundle

      - run:
          name: Database setup
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load

      - run:
          name: Run tests
          command: bundle exec rspec # or whatever your test command is
