development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://dev_redis:6379/1" } %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDISCLOUD_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: video_production
