development:
  adapter: redis
  url: <%= ENV.fetch("REDISCLOUD_URL") { "redis://dev_redis:6379/1" } %>

test:
  adapter: redis
  url: <%= ENV.fetch("REDISCLOUD_URL") { "redis://localhost:6379/1" } %>

production:
  adapter: redis
  url: <%= ENV.fetch("REDISCLOUD_URL") { "redis://default:TgaimxAcKd5YC7RbN2J8I5mD5bji9KCQ@redis-13465.c9.us-east-1-2.ec2.cloud.redislabs.com:13465" } %>
  channel_prefix: video_production
