default: &default
  adapter: postgresql
  encoding: unicode
  # username: <%= ENV['POSTGRES_USER'] %>
  # password: <%= ENV['POSTGRES_PASSWORD'] %>
  # host: <%= ENV['DB_HOST'] %
  username: 'camnguyen1'
  password: '123123'
  host: 'localhost'
development:
  <<: *default
  database: test3

test:
  <<: *default
  database: test3

production:
  <<: *default
  database: test3
